### ISSUE TITLE
!remind doesn't update to new usernames

### ISSUE THREAD

**Issue by hrfarmer** [Sheepposu/offlinechatbot#4]
THE BOT IS DEADNAMING ME!!!
(it's just the title, i made a reminder and it pinged my old username instead of current one, and i didn't get the @ because of it)

<img width="445" alt="image" src="https://github.com/Sheppsu/offlinechatbot/assets/58487401/0397db1a-f47a-4a79-9634-f7e8fbce7b73">

also first issue (idk if you even want people to make issues for the bot here but i already had the github page open and you were offline so yea)

**Comment by Sheppsu** [comment]
Resolved by https://github.com/Sheppsu/offlinechatbot/commit/7e3ba3f977343e49657a3dcbac4ab8d599580ccf
